var data = [
	    {No:1,Name:'George Washington',Party:'none'},
	    {No:2,Name:'John Adams',Party:'Federalist'},          
	    {No:3,Name:'Thomas Jefferson',Party:'Democratic-Republican'},
	    {No:4,Name:'James Madison',Party:'Democratic-Republican'},
	    {No:5,Name:'James Monroe',Party:'Democratic-Republican'},
	    {No:6,Name:'John Quincy Adams',Party:'Democratic-Republican'},
	    {No:7,Name:'Andrew Jackson',Party:'Democratic'},
	    {No:8,Name:'Martin Van Buren',Party:'Democratic'},
	    {No:9,Name:'William Henry Harrison',Party:'Whig'},
	    {No:10,Name:'John Tyler',Party:'Whig'},
	    {No:11,Name:'James K. Polk',Party:'Democratic'},
	    {No:12,Name:'Zachary Taylor',Party:'Whig'},
	    {No:13,Name:'Millard Fillmore',Party:'Whig'},
	    {No:14,Name:'Franklin Pierce',Party:'Democratic'},
	    {No:15,Name:'James Buchanan',Party:'Democratic'},
	    {No:16,Name:'Abraham Lincoln',Party:'Republican'},
	    {No:17,Name:'Andrew Johnson',Party:'Democratic'},
	    {No:18,Name:'Ulysses S. Grant',Party:'Republican'},
	    {No:19,Name:'Rutherford B. Hayes',Party:'Republican'},
	    {No:20,Name:'James A. Garfield',Party:'Republican'},
	    {No:21,Name:'Chester A. Arthur',Party:'Republican'},
	    {No:22,Name:'Grover Cleveland',Party:'Democratic'},
	    {No:23,Name:'Benjamin Harrison',Party:'Republican'},
	    {No:24,Name:'Grover Cleveland',Party:'Democratic'},
	    {No:25,Name:'William McKinley',Party:'Republican'},
	    {No:26,Name:'Theodore Roosevelt',Party:'Republican'},
	    {No:27,Name:'William Howard Taft',Party:'Republican'},
	    {No:28,Name:'Woodrow Wilson',Party:'Democratic'},
	    {No:29,Name:'Warren G. Harding',Party:'Republican'},
	    {No:30,Name:'Calvin Coolidge',Party:'Republican'},
	    {No:31,Name:'Herbert Hoover',Party:'Republican'},
	    {No:32,Name:'Franklin D. Roosevelt',Party:'Democratic'},
	    {No:33,Name:'Harry S. Truman',Party:'Democratic'},
	    {No:34,Name:'Dwight D. Eisenhower',Party:'Republican'},
	    {No:35,Name:'John F. Kennedy',Party:'Democratic'},
	    {No:36,Name:'Lyndon B. Johnson',Party:'Democratic'},
	    {No:37,Name:'Richard Nixon',Party:'Republican'},
	    {No:38,Name:'Gerald Ford',Party:'Republican'},
	    {No:39,Name:'Jimmy Carter',Party:'Democratic'},
	    {No:40,Name:'Ronald Reagan',Party:'Republican'},
	    {No:41,Name:'George H. W. Bush',Party:'Republican'},
	    {No:42,Name:'Bill Clinton',Party:'Democratic'},
	    {No:43,Name:'George W. Bush',Party:'Republican'},
	    {No:44,Name:'Barack Obama',Party:'Democratic'}
	   ];